#! /bin/bash

# Create new folder if one is given
if [ "$1" != "." ] && [ "$1" != "" ]; then
	mkdir $1
	cd $1
fi

# Remove first parameter
shift

# Clone wpprojectcreator
git clone git://github.com/boyvanamstel/Wordpress-Project-Creator.git .

# Run it with parameters
python wpprojectcreator.py $@
